name: Static Site CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '18'

      - name: Install markdownlint
        run: npm install -g markdownlint-cli

      - name: Lint Markdown files
        run: markdownlint "*.md" --ignore node_modules || true

      - name: Check YAML files
        run: |
          sudo apt-get install yamllint
          find . -name "*.yml" -o -name "*.yaml" | xargs yamllint || true

  validate-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate HTML
        run: |
          sudo apt-get install tidy
          find . -name "*.html" -exec tidy -q -e {} \; || true